#!/bin/bash

# Path to the colors file generated by wal
colors_rasi_file="$HOME/.cache/wal/colors"

# List of Rofi theme files to update
rofi_theme_files=(
    "$HOME/.config/rofi/powermenu/type-6/style-1.rasi"
    "$HOME/.config/rofi/powermenu/type-6/style-2.rasi"
    "$HOME/.config/rofi/powermenu/type-6/style-3.rasi"
    "$HOME/.config/rofi/powermenu/type-6/style-4.rasi"
    "$HOME/.config/rofi/powermenu/type-6/style-5.rasi"

    "$HOME/.config/rofi/launchers/type-7/style-1.rasi"
    "$HOME/.config/rofi/launchers/type-7/style-2.rasi"
    "$HOME/.config/rofi/launchers/type-7/style-3.rasi"
    "$HOME/.config/rofi/launchers/type-7/style-4.rasi"
    "$HOME/.config/rofi/launchers/type-7/style-5.rasi"
    "$HOME/.config/rofi/launchers/type-7/style-6.rasi"
    "$HOME/.config/rofi/launchers/type-7/style-7.rasi"
    "$HOME/.config/rofi/launchers/type-7/style-8.rasi"
    "$HOME/.config/rofi/launchers/type-7/style-9.rasi"
    "$HOME/.config/rofi/launchers/type-7/style-10.rasi"

    "$HOME/.config/rofi/launchers/type-6/style-1.rasi"
    "$HOME/.config/rofi/launchers/type-6/style-2.rasi"
    "$HOME/.config/rofi/launchers/type-6/style-3.rasi"
    "$HOME/.config/rofi/launchers/type-6/style-4.rasi"
    "$HOME/.config/rofi/launchers/type-6/style-5.rasi"
    "$HOME/.config/rofi/launchers/type-6/style-6.rasi"
    "$HOME/.config/rofi/launchers/type-6/style-7.rasi"
    "$HOME/.config/rofi/launchers/type-6/style-8.rasi"
    "$HOME/.config/rofi/launchers/type-6/style-9.rasi"
    "$HOME/.config/rofi/launchers/type-6/style-10.rasi"
)

# Check if the colors file exists and is not empty
if [ ! -f "$colors_rasi_file" ] || [ ! -s "$colors_rasi_file" ]; then
    echo "Error: $colors_rasi_file does not exist or is empty."
    exit 1
fi

# Extract colors from the wal colors file
background=$(sed -n '1p' "$colors_rasi_file")
background_alt=$(sed -n '9p' "$colors_rasi_file")
foreground=$(sed -n '16p' "$colors_rasi_file")
selected=$(sed -n '12p' "$colors_rasi_file")
active=$(sed -n '11p' "$colors_rasi_file")
urgent=$(sed -n '3p' "$colors_rasi_file")

# Escape special characters in color values for sed
background=$(echo "$background" | sed 's/[&/\]/\\&/g')
background_alt=$(echo "$background_alt" | sed 's/[&/\]/\\&/g')
foreground=$(echo "$foreground" | sed 's/[&/\]/\\&/g')
selected=$(echo "$selected" | sed 's/[&/\]/\\&/g')
active=$(echo "$active" | sed 's/[&/\]/\\&/g')
urgent=$(echo "$urgent" | sed 's/[&/\]/\\&/g')

# Debugging: Print the extracted color values
echo "Background: $background"
echo "Background-alt: $background_alt"
echo "Foreground: $foreground"
echo "Selected: $selected"
echo "Active: $active"
echo "Urgent: $urgent"

# Loop over each Rofi theme file and update the colors
for rofi_theme_file in "${rofi_theme_files[@]}"; do
    # Check if the Rofi theme file exists and is writable
    if [ ! -f "$rofi_theme_file" ] || [ ! -w "$rofi_theme_file" ]; then
        echo "Error: $rofi_theme_file does not exist or is not writable."
        continue
    fi

    # Replace the colors in the Rofi theme file
    sed -i "s|background:.*|background: $background;|" "$rofi_theme_file"
    sed -i "s|background-alt:.*|background-alt: $background_alt;|" "$rofi_theme_file"
    sed -i "s|foreground:.*|foreground: $foreground;|" "$rofi_theme_file"
    sed -i "s|selected:.*|selected: $selected;|" "$rofi_theme_file"
    sed -i "s|active:.*|active: $active;|" "$rofi_theme_file"
    sed -i "s|urgent:.*|urgent: $urgent;|" "$rofi_theme_file"

    # Output result for each file
    echo "Rofi theme updated successfully with colors from $colors_rasi_file for file: $rofi_theme_file"
done
