cp -r .config/rofi/images/current.jpg .config/rofi/images/a.png
cp -r .config/rofi/images/current.jpg .config/rofi/images/b.png
cp -r .config/rofi/images/current.jpg .config/rofi/images/c.png
cp -r .config/rofi/images/current.jpg .config/rofi/images/d.png
cp -r .config/rofi/images/current.jpg .config/rofi/images/e.jpg
cp -r .config/rofi/images/current.jpg .config/rofi/images/f.png
cp -r .config/rofi/images/current.jpg .config/rofi/images/g.png
cp -r .config/rofi/images/current.jpg .config/rofi/images/h.jpg
cp -r .config/rofi/images/current.jpg .config/rofi/images/i.jpg
cp -r .config/rofi/images/current.jpg .config/rofi/images/j.jpg
